
# Note : This mariadb relies on init.sql to create the initial access for the server.
# The server then uses that access to create the databases and tables.
# In a production environment, you would want to then implement a secondary server-access permission
# to prevent unauthorized actions being taken on the database in the case that is compromised.
services:
  psc-mariadb:
    image: mariadb:latest
    container_name: psc-mariadb
    #env_file: .env  # Specify the .env file to use to define environment variables
    environment:
      - MARIADB_ROOT_PASSWORD=root_password
      # We set the political-scorecard-backend to use the base SQL database to create the context and location databases and all others.
      # Therefore, no need to create a default database here.
      #- MYSQL_DATABASE=your_database_name
      #- MYSQL_USER=root
      #- MYSQL_PASSWORD=root_password
    ports:
      - "3800:3306"
    volumes:
      - db-data:/var/lib/mysql
      - /init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  default:
    external: # What is an external network? https://docs.docker.com/compose/networking/#use-a-pre-existing-network
      name: political-scorecard-network

volumes:
  db-data: